
spring:
  mvc:
    favicon:
      enabled: false
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: gson
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    schema: # schema.sql中一般存放的是DDL脚本，即通常为创建或更新库表的脚本
      - classpath:sql/schema.sql
      - classpath:sql/schema-2020-03-18.sql
    data: classpath:sql/data.sql # data.sql中一般是DML脚本，即通常为数据插入脚本
    initialization-mode: always # spring某个版本之后需要加上这句，否则不会自动执行sql文件
    separator: $$
    # hikari配置
    hikari:
      auto-commit: true
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
      minimum-idle: 5
      maximum-pool-size: 20
# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.hinz.blog.model
  type-enums-package: com.hinz.blog.model.enums
  global-config:
    # 数据库相关配置
    db-config:
      # 数据库表前缀
      table-prefix: blog_
      #主键类型
      id-type: auto
      #数据库类型
      db-type: mysql
    banner: false



github:
  clientId: 4c8e5c108b41ce024f46
  clientSecret: 054f0ab71f8622081bfca2b583b35cb977fc90b6
  redirectUri: http://localhost:8081/authorize/redirect
  authorizeUrl: https://github.com/login/oauth/authorize?client_id=clientId&redirect_uri=redirectUri
  accesstokenUrl: https://github.com/login/oauth/access_token?client_id=clientId&client_secret=clientSecret&code=authorize_code
  userUrl: https://api.github.com/user